### ISSUE TITLE
Better Fallbacks for language handlers in View

### ISSUE THREAD

**Issue by DanielWeitenauer** [studio-ahoi/_ahoi_tools#1]
Fallback language is 0. It would be more user-friendly to make this selectable for each field.

**Comment by Sysix-Coding** [comment]
Info for you :)
Fallback language is not allways 0. If you deleted the default language, you have a other id.
Maybe you can use [$REX['START_CLANG_ID']](https://github.com/redaxo/redaxo4/blob/master/redaxo/include/master.inc.php#L48).

**Comment by DanielWeitenauer** [comment]
Another reason to improve this :)
